from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scoreboard(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1988, 937)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_member_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_member_2.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"")
        self.frame_member_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_member_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_member_2.setObjectName("frame_member_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_member_2)
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_member_2 = QtWidgets.QLabel(self.frame_member_2)
        self.label_member_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(55)
        font.setBold(True)
        font.setWeight(75)
        self.label_member_2.setFont(font)
        self.label_member_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_member_2.setObjectName("label_member_2")
        self.verticalLayout_3.addWidget(self.label_member_2)
        self.label_team_2 = QtWidgets.QLabel(self.frame_member_2)
        self.label_team_2.setMinimumSize(QtCore.QSize(1000, 60))
        self.label_team_2.setMaximumSize(QtCore.QSize(1000, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_team_2.setFont(font)
        self.label_team_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_team_2.setObjectName("label_team_3")
        self.verticalLayout_3.addWidget(self.label_team_2)
        self.label_winer_2 = QtWidgets.QLabel(self.frame_member_2)
        self.label_winer_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_winer_2.setFont(font)
        self.label_winer_2.setStyleSheet("color: rgb(255, 217, 0);")
        self.label_winer_2.setText("")
        self.label_winer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_winer_2.setObjectName("label_winer_3")
        self.verticalLayout_3.addWidget(self.label_winer_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.label_score_2 = QtWidgets.QLabel(self.frame_member_2)
        self.label_score_2.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(150)
        font.setBold(True)
        font.setWeight(75)
        self.label_score_2.setFont(font)
        self.label_score_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_score_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_2.setObjectName("label_score_2")
        self.horizontalLayout_3.addWidget(self.label_score_2)
        self.fine_layout_2 = QtWidgets.QHBoxLayout()
        self.fine_layout_2.setContentsMargins(-1, 40, 0, 40)
        self.fine_layout_2.setSpacing(30)
        self.fine_layout_2.setObjectName("fine_layout_2")
        self.label_card_2_1 = QtWidgets.QLabel(self.frame_member_2)
        self.label_card_2_1.setMinimumSize(QtCore.QSize(125, 200))
        self.label_card_2_1.setMaximumSize(QtCore.QSize(125, 200))
        self.label_card_2_1.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_card_2_1.setText("")
        self.label_card_2_1.setObjectName("label_card_2_1")
        self.fine_layout_2.addWidget(self.label_card_2_1)
        self.label_card_2_2 = QtWidgets.QLabel(self.frame_member_2)
        self.label_card_2_2.setMinimumSize(QtCore.QSize(125, 200))
        self.label_card_2_2.setMaximumSize(QtCore.QSize(125, 200))
        self.label_card_2_2.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_card_2_2.setText("")
        self.label_card_2_2.setObjectName("label_card_2_2")
        self.fine_layout_2.addWidget(self.label_card_2_2)
        self.horizontalLayout_3.addLayout(self.fine_layout_2)
        self.gridLayout.addWidget(self.frame_member_2, 1, 0, 1, 1)
        self.frame_everyone = QtWidgets.QFrame(self.centralwidget)
        self.frame_everyone.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_everyone.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_everyone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_everyone.setObjectName("frame_everyone")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_everyone)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_total_time = QtWidgets.QLabel(self.frame_everyone)
        font = QtGui.QFont()
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.label_total_time.setFont(font)
        self.label_total_time.setStyleSheet("color: rgb(136, 255, 0);")
        self.label_total_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_time.setObjectName("label_total_time")
        self.gridLayout_2.addWidget(self.label_total_time, 0, 1, 2, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_hold_time = QtWidgets.QLabel(self.frame_everyone)
        font = QtGui.QFont()
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.label_hold_time.setFont(font)
        self.label_hold_time.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_hold_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hold_time.setObjectName("label_hold_time")
        self.verticalLayout_4.addWidget(self.label_hold_time)
        self.label_hold = QtWidgets.QLabel(self.frame_everyone)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_hold.setFont(font)
        self.label_hold.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_hold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hold.setObjectName("label_hold")
        self.verticalLayout_4.addWidget(self.label_hold)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 4, 2, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_weight_category = QtWidgets.QLabel(self.frame_everyone)
        font = QtGui.QFont()
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.label_weight_category.setFont(font)
        self.label_weight_category.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_weight_category.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_weight_category.setObjectName("label_weight_category")
        self.verticalLayout_6.addWidget(self.label_weight_category)
        self.label = QtWidgets.QLabel(self.frame_everyone)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_weight_category_name = QtWidgets.QLabel(self.frame_everyone)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_weight_category_name.setFont(font)
        self.label_weight_category_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_weight_category_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_weight_category_name.setObjectName("label_weight_category_name")
        self.verticalLayout_6.addWidget(self.label_weight_category_name)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 2, 1)
        self.gridLayout.addWidget(self.frame_everyone, 2, 0, 1, 1)
        self.frame_member_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_member_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.frame_member_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_member_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_member_1.setObjectName("frame_member_1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_member_1)
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_member_1 = QtWidgets.QLabel(self.frame_member_1)
        self.label_member_1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(55)
        font.setBold(True)
        font.setWeight(75)
        self.label_member_1.setFont(font)
        self.label_member_1.setStyleSheet("color: rgb(0, 0, 255);\n"
"")
        self.label_member_1.setObjectName("label_member_1")
        self.verticalLayout.addWidget(self.label_member_1)
        self.label_team_1 = QtWidgets.QLabel(self.frame_member_1)
        self.label_team_1.setMinimumSize(QtCore.QSize(1000, 60))
        self.label_team_1.setMaximumSize(QtCore.QSize(1000, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_team_1.setFont(font)
        self.label_team_1.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_team_1.setObjectName("label_team_1")
        self.verticalLayout.addWidget(self.label_team_1)
        self.label_winer_1 = QtWidgets.QLabel(self.frame_member_1)
        self.label_winer_1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_winer_1.setFont(font)
        self.label_winer_1.setStyleSheet("color: rgb(255, 217, 0);")
        self.label_winer_1.setText("")
        self.label_winer_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_winer_1.setObjectName("label_winer_1")
        self.verticalLayout.addWidget(self.label_winer_1)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.label_score_1 = QtWidgets.QLabel(self.frame_member_1)
        self.label_score_1.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(150)
        font.setBold(True)
        font.setWeight(75)
        self.label_score_1.setFont(font)
        self.label_score_1.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_score_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score_1.setObjectName("label_score_1")
        self.horizontalLayout_4.addWidget(self.label_score_1)
        self.fine_layout_1 = QtWidgets.QHBoxLayout()
        self.fine_layout_1.setContentsMargins(-1, 40, -1, 40)
        self.fine_layout_1.setSpacing(30)
        self.fine_layout_1.setObjectName("fine_layout_1")
        self.label_card_1_1 = QtWidgets.QLabel(self.frame_member_1)
        self.label_card_1_1.setMinimumSize(QtCore.QSize(125, 200))
        self.label_card_1_1.setMaximumSize(QtCore.QSize(125, 200))
        self.label_card_1_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_card_1_1.setText("")
        self.label_card_1_1.setObjectName("label_card_1_1")
        self.fine_layout_1.addWidget(self.label_card_1_1)
        self.label_card_1_2 = QtWidgets.QLabel(self.frame_member_1)
        self.label_card_1_2.setMinimumSize(QtCore.QSize(125, 200))
        self.label_card_1_2.setMaximumSize(QtCore.QSize(125, 200))
        self.label_card_1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_card_1_2.setText("")
        self.label_card_1_2.setObjectName("label_card_1_2")
        self.fine_layout_1.addWidget(self.label_card_1_2)
        self.horizontalLayout_4.addLayout(self.fine_layout_1)
        self.gridLayout.addWidget(self.frame_member_1, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_member_2.setText(_translate("MainWindow", ""))
        self.label_score_2.setText(_translate("MainWindow", "0"))
        self.label_total_time.setText(_translate("MainWindow", "00:00"))
        self.label_hold_time.setText(_translate("MainWindow", "0.0"))
        self.label_hold.setText(_translate("MainWindow", "УДЕРЖАНИЕ"))
        self.label_weight_category.setText(_translate("MainWindow", ""))
        self.label.setText(_translate("MainWindow", "ВЕСОВАЯ"))
        self.label_weight_category_name.setText(_translate("MainWindow", "КАТЕГОРИЯ"))
        self.label_member_1.setText(_translate("MainWindow", ""))
        self.label_score_1.setText(_translate("MainWindow", "0"))
        self.label_team_1.setText(_translate("MainWindow", "ВЫБЕРИТЕ ВЕСОВУЮ КАТЕГОРИЮ И ГРУППУ"))
        self.label_team_2.setText(_translate("MainWindow", "ВЫБЕРИТЕ ВЕСОВУЮ КАТЕГОРИЮ И ГРУППУ"))

