
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VisitWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.pushButton_new_scoreboard = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_new_scoreboard.setFont(font)
        self.pushButton_new_scoreboard.setObjectName("pushButton_new_scoreboard")
        self.gridLayout.addWidget(self.pushButton_new_scoreboard, 1, 0, 1, 1)
        self.pushButton_members_list = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_members_list.setFont(font)
        self.pushButton_members_list.setObjectName("pushButton_members_list")
        self.gridLayout.addWidget(self.pushButton_members_list, 3, 0, 1, 1)
        self.pushButton_close_all_scoreboards = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_close_all_scoreboards.setFont(font)
        self.pushButton_close_all_scoreboards.setObjectName("pushButton_close_all_scoreboards")
        self.gridLayout.addWidget(self.pushButton_close_all_scoreboards, 1, 1, 1, 1)
        self.pushButton_load_data = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_load_data.setFont(font)
        self.pushButton_load_data.setObjectName("pushButton_load_data")
        self.gridLayout.addWidget(self.pushButton_load_data, 3, 1, 1, 1)
        self.pushButton_generate_diploma = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_generate_diploma.setFont(font)
        self.pushButton_generate_diploma.setObjectName("pushButton_generate_diploma")
        self.gridLayout.addWidget(self.pushButton_generate_diploma, 4, 0, 1, 1)
        self.pushButton_export_table = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_export_table.setFont(font)
        self.pushButton_export_table.setObjectName("pushButton_export_table")
        self.gridLayout.addWidget(self.pushButton_export_table, 4, 1, 1, 1)
        self.pushButton_close_app = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_close_app.setFont(font)
        self.pushButton_close_app.setObjectName("pushButton_close_app")
        self.gridLayout.addWidget(self.pushButton_close_app, 5, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Табло </span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">для соревнований</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">по дзюдо</span></p></body></html>"))
        self.pushButton_new_scoreboard.setText(_translate("MainWindow", "Новое табло"))
        self.pushButton_members_list.setText(_translate("MainWindow", "Список участников"))
        self.pushButton_close_all_scoreboards.setText(_translate("MainWindow", "Закрыть все табло"))
        self.pushButton_load_data.setText(_translate("MainWindow", "Загрузить данные"))
        self.pushButton_generate_diploma.setText(_translate("MainWindow", "Создать грамоту"))
        self.pushButton_export_table.setText(_translate("MainWindow", "Экспорт результатов"))
        self.pushButton_close_app.setText(_translate("MainWindow", "Закрыть программу"))

