
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 786)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listView_members_list = QtWidgets.QListView(self.centralwidget)
        self.listView_members_list.setObjectName("listView_members_list")
        self.gridLayout.addWidget(self.listView_members_list, 3, 0, 1, 2)
        self.label_name_weight_category = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_weight_category.setFont(font)
        self.label_name_weight_category.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name_weight_category.setObjectName("label_name_weight_category")
        self.gridLayout.addWidget(self.label_name_weight_category, 1, 0, 1, 1)
        self.comboBox_weight_category = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_weight_category.setFont(font)
        self.comboBox_weight_category.setEditable(False)
        self.comboBox_weight_category.setObjectName("comboBox_weight_category")
        self.comboBox_weight_category.addItem("")
        self.comboBox_weight_category.addItem("")
        self.comboBox_weight_category.addItem("")
        self.comboBox_weight_category.addItem("")
        self.gridLayout.addWidget(self.comboBox_weight_category, 1, 1, 1, 1)
        self.comboBox_group = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_group.setFont(font)
        self.comboBox_group.setEditable(False)
        self.comboBox_group.setObjectName("comboBox_group")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.gridLayout.addWidget(self.comboBox_group, 2, 1, 1, 1)
        self.label_name_group = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_group.setFont(font)
        self.label_name_group.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name_group.setObjectName("label_name_group")
        self.gridLayout.addWidget(self.label_name_group, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name_weight_category.setText(_translate("MainWindow", "Весовая категория"))
        self.comboBox_weight_category.setCurrentText(_translate("MainWindow", "22"))
        self.comboBox_weight_category.setItemText(0, _translate("MainWindow", "22"))
        self.comboBox_weight_category.setItemText(1, _translate("MainWindow", "24"))
        self.comboBox_weight_category.setItemText(2, _translate("MainWindow", "26"))
        self.comboBox_weight_category.setItemText(3, _translate("MainWindow", "28"))
        self.comboBox_group.setCurrentText(_translate("MainWindow", "А"))
        self.comboBox_group.setItemText(0, _translate("MainWindow", "А"))
        self.comboBox_group.setItemText(1, _translate("MainWindow", "Б"))
        self.comboBox_group.setItemText(2, _translate("MainWindow", "В"))
        self.comboBox_group.setItemText(3, _translate("MainWindow", "Г"))
        self.label_name_group.setText(_translate("MainWindow", "Группа"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
